version: 2
applyMode: newTabs
groupingStrategy: inheritFirst
shortcuts:
  slots:
    - "Work"
    - "Search"
    - "Personal"

groups:
  - name: Work
    color: blue
    cleanup:
      ttlMinutes: 180
      maxTabs: 20
      lru: true
    rules:
      - pattern: '*github.com*'
      - pattern: '*gitlab.com*'
      - pattern: '*bitbucket.org*'
      - pattern: '*atlassian.net*'
      - pattern: '*linear.app*'

  - name: Docs
    color: green
    rules:
      - pattern: '*docs.google.com*'
      - pattern: '*notion.so*'
      - pattern: '*qiita.com*'
      - pattern: '*zenn.dev*'

  - name: Search
    color: red
    rules:
      - pattern: '*google.*/search*'
      - pattern: '*bing.com/search*'
      - pattern: '*duckduckgo.com/*'

  - name: Media
    color: purple
    rules:
      - pattern: '*youtube.com*'
      - pattern: '*netflix.com*'

  - name: Social
    color: orange
    rules:
      - pattern: '*x.com*'
      - pattern: '*twitter.com*'
